# Generated by Django 3.1 on 2020-10-29 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convite',
            name='recebidos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos', to='perfil.perfil'),
        ),
        migrations.AlterField(
            model_name='convite',
            name='solicitados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_feitos', to='perfil.perfil'),
        ),
    ]
