# Generated by Django 3.1 on 2020-11-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_remove_postagem_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='texto',
            field=models.TextField(),
        ),
    ]
